### PR TITLE
CNN tutorial

### PR DESCRIPTION
**Pull request by thaarres**
Tutorial on CNNs in hls4ml, based on https://iopscience.iop.org/article/10.1088/2632-2153/ac0ea1

### CODE REVIEW

**Comment by thaarres** [comment]
Could @thesps, @vloncar, @nicologhielmetti , @jmduarte have a look and let me know if anything is missing/should be corrected?

**Comment by vloncar** [comment]
Thanks Thea, this looks great. BTW, since we merged [line-buffer](https://github.com/fastmachinelearning/hls4ml/pull/332) implementation the way algorithm works (by default) has been changed so we should use the new animation from that PR.

**Comment by thaarres** [comment]
@thesps anything missng to merge this?

**Comment by thesps** [comment]
This was included in #23, so now merged. Closing this one!

**Pull request closed without merging**
